#!/bin/sh
sudo make
if [ $? -eq 0 ]; then
read -p "Press \"Enter\" ..." xyz
killall -w kicker
sudo \cp showdeskten_applet.desktop /opt/trinity/share/apps/kicker/applets/showdeskten_applet.desktop
sudo \cp .libs/showdeskten_applet_panelapplet.lai /opt/trinity/lib/trinity/showdeskten_applet_panelapplet.la
sudo \cp .libs/showdeskten_applet_panelapplet.so /opt/trinity/lib/trinity/showdeskten_applet_panelapplet.so
kicker &
echo "done."
else
echo "make error."
fi


